name: compact_color_picker
description: A simple & clean color picker widget with opacity for Flutter. Designed to be powerful yet compact (mobile-first), suitable for all platforms!
version: 1.0.2 # Updated version
homepage: https://github.com/BrayFlex/compact_color_picker # Assuming this is the repo URL
repository: https://github.com/BrayFlex/compact_color_picker # Add repository URL

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
